/**
 * Verbatim transcription of the IDU REST API documentation's "List of error
 * codes" appendix (page 85-91). Gaps in the numeric sequence are the doc's
 * own — not omissions here. "X" is the doc's own placeholder token for
 * field names/limits, left as-is.
 */
export const ERROR_CODES: Record<number, string> = {
  1000: 'The name must be a string',
  1001: 'The name field is required',
  1002: 'The name must not be greater than X characters',
  1003: 'The description must be a string',
  1004: 'The description must not be greater than X characters',
  1005: 'The report_type_id field is required',
  1006: 'The report_type_id must be a string',
  1007: 'The forename field is required',
  1008: 'The forename must be a string',
  1009: 'The middlename must be a string',
  1010: 'The surname field is required',
  1011: 'The surname must be a string',
  1012: 'The dob field is required',
  1013: 'The dob is not a valid date',
  1014: 'The address.address1 field is required',
  1015: 'The address.address1 must be a string',
  1016: 'The address.address2 must be a string',
  1017: 'The address.address3 must be a string',
  1018: 'The address.address4 must be a string',
  1019: 'The address.address5 must be a string',
  1020: 'The address.postcode field is required',
  1021: 'The address.postcode must be a string',
  1022: 'The address field must be true or false',
  1023: 'The lexid field must be true or false',
  1024: 'The full_address must be a string',
  1025: 'The full_address must not be greater than X characters',
  1026: 'The house must be a string',
  1027: 'The house must not be greater than X characters',
  1028: 'The street must be a string',
  1029: 'The street must not be greater than X characters',
  1030: 'The town must be a string',
  1031: 'The town must not be greater than X characters',
  1032: 'The postcode must be a string',
  1033: 'The postcode must not be greater than X characters',
  1034: 'The fuzzy field must be true or false',
  1035: 'The alias field must be true or false',
  1036: 'The primary_actions must be an array',
  1037: 'The X report action does not exist',
  1038: 'The primary_actions field has a duplicate value',
  1039: 'The X report action is not enabled for your user',
  1040: 'The fuzzy_matching field must be true or false',
  1042: 'The alias_matching field must be true or false',
  1044: 'The date_from is not a valid date',
  1045: 'The date_to is not a valid date',
  1046: 'The full_er field must be true or false',
  1047: 'The dob field must be true or false',
  1048: 'The credit_activity field must be true or false',
  1049: 'The reference must be a string',
  1050: 'The death field must be true or false',
  1051: 'The ddri field must be true or false',
  1052: 'The dob field is required when X is not present',
  1053: 'The address.address1 field is required when X is not present',
  1054: 'The address.postcode field is required when X is not present',
  1055: 'The enduser_agreement field is required',
  1056: 'The enduser_agreement field must be true or false',
  1057: 'The ccj field must be true or false',
  1058: 'The insolvency field must be true or false',
  1074: 'The experian field must be true or false',
  1075: 'The equifax field must be true or false',
  1076: 'The director field must be true or false',
  1077: 'The per_page must be an integer',
  1078: 'The per_page must be at least X',
  1079: 'The per_page must not be greater than X',
  1080: 'The page must be an integer',
  1081: 'The page must be at least X',
  1082: 'The credit_active_mode is not valid',
  1083: 'The credit_active_primary is not valid',
  1085: 'The sanction field must be true or false',
  1086: 'The pep field must be true or false',
  1093: 'The bank_details.sort_code field is required',
  1094: 'The bank_details.sort_code must be a string',
  1095: 'The bank_details.sort_code must be X digits',
  1096: 'The bank_details.account_number field is required',
  1097: 'The bank_details.account_number must be a string',
  1098: 'The bank_details.account_number must be X digits',
  1099: 'The bankaccount field must be true or false',
  1100: 'The td field must be true or false',
  1101: 'The xd field must be true or false',
  1104: 'The email_risk field must be true or false',
  1105: 'The emails must be an array',
  1106: 'The emails must not be greater than X characters',
  1107: 'The emails.email field is required',
  1108: 'The emails.email must be a valid email address',
  1109: 'The emails.email field has a duplicate value',
  1110: 'The emails field is required',
  1111: 'The role value is not a valid role',
  1113: 'The age_min must be an integer',
  1114: 'The age_min must be at least X',
  1115: 'The age_min must be less than X',
  1116: 'The age_max must be an integer',
  1117: 'The age_max must be at least X',
  1118: 'The age_max must be less than X',
  1119: 'The age_min must be less than or equal X',
  1120: 'The age field must be true or false',
  1121: 'The path_identifier must be a string',
  1122: 'The method must be a string',
  1123: 'The path must be a string',
  1124: 'The ip must be a string',
  1125: 'The status must be an integer',
  1126: 'The user_id must be an integer',
  1127: 'The company_id must be an integer',
  1128: 'The forename must not be greater than X characters',
  1129: 'The middlename must not be greater than X characters',
  1130: 'The surname must not be greater than X characters',
  1131: 'The address.address1 must not be greater than X characters',
  1132: 'The address.address2 must not be greater than X characters',
  1133: 'The address.address3 must not be greater than X characters',
  1134: 'The address.address4 must not be greater than X characters',
  1135: 'The address.address5 must not be greater than X characters',
  1136: 'The address.postcode must not be greater than X characters',
  1137: 'The reference must not be greater than X characters',
  1138: 'The username must not be greater than X characters',
  1139: 'The path_identifier must not be greater than X characters',
  1140: 'The method must not be greater than X characters',
  1141: 'The path must not be greater than X characters',
  1142: 'The ip must not be greater than X characters',
  1143: 'The server_name must not be greater than X characters',
  1145: 'The include_empty_postcode must be between X and X characters',
  1146: 'The include_empty_dob must be between X and X characters',
  1147: 'The include_empty_postcode must be an integer',
  1148: 'The include_empty_dob must be an integer',
  1149: 'The report_type_id field prohibits X from being present',
  1150: 'The actions must be an array',
  1151: 'The actions field has a duplicate value',
  1152: 'The X report action does not exist',
  1153: 'The X report action is not enabled for your user',
  1154: 'The application must be a string',
  1155: 'The application must not be greater than X characters',
  1156: 'The level must be a string',
  1157: 'The level must not be greater than X characters',
  1158: 'The channel must be a string',
  1159: 'The channel must not be greater than X characters',
  1160: 'The config.full_er field must be true or false',
  1161: 'The config.full_er is a setting you do not have permission to use',
  1162: 'The pass_threshold must be an integer',
  1163: 'The scorecard pass threshold must be greater than the failure threshold',
  1164: 'The fail_threshold must be an integer',
  1165: 'The groups must be an array',
  1166: 'The groups.group_name field has a duplicate value',
  1167: 'The groups.group_name must be a string',
  1168: 'The groups.min_score must be an integer',
  1169: 'The groups.rules must be an array',
  1170: 'The groups.rules.attribute field is required',
  1171: 'The groups.rules.attribute is not a valid report attribute',
  1172: 'The groups.rules.attribute contains a report attribute that you do not have permission to use',
  1173: 'The groups.rules contains a duplicate rule',
  1174: 'The groups.rules.match_score must be an integer',
  1175: 'The groups.rules.no_match_score must be an integer',
  1176: 'The groups.group_name must be at least X characters',
  1177: 'The groups.group_name must not be greater than X characters',
  1178: 'The scorecard_id must be a string',
  1179: 'The scorecard_id is invalid',
  1180: 'The address_insights field must be true or false',
  1181: 'The address_lookup field must be true or false',
  1182: 'The report_id must be a string',
  1183: 'The report_id must not be greater than X characters',
  1184: 'The url must be a string',
  1185: 'The url must not be greater than X characters',
  1186: 'The username must be a string',
  1187: 'The resource must be a valid UUID',
  1190: 'The message must be a string',
  1191: 'The message must not be greater than X characters',
  1192: 'The message field is required',
  1193: 'The config.age_min must be at least X characters',
  1194: 'The config.age_min must be less than X characters',
  1195: 'The config.age_max must be at least X characters',
  1196: 'The config.age_max must be less than X characters',
  1197: 'The config.age_min must be less than the X',
  1198: 'The config.age_max must be greater than the X',
  1199: 'The bank_account_validation field must be true or false',
  1200: 'The driving_licence_validation field must be true or false',
  1201: 'The ni_number_validation field must be true or false',
  1202: 'The passport_validation field must be true or false',
  1203: 'The ni_number field is required',
  1204: 'The ni_number must be a string',
  1205: 'The config.age_min must be an integer',
  1206: 'The config.age_max must be an integer',
  1207: 'The scorecard_id must be a valid UUID',
  1208: 'The gender field is required',
  1209: 'The gender must be a string',
  1210: 'The selected gender is invalid',
  1211: 'The passport.mrz_line2.part1 field is required',
  1212: 'The passport.mrz_line2.part1 must be a string',
  1213: 'The passport.mrz_line2.part1 must be X characters',
  1214: 'The passport.mrz_line2.part2 field is required',
  1215: 'The passport.mrz_line2.part2 must be a string',
  1216: 'The passport.mrz_line2.part2 must be X characters',
  1217: 'The passport.mrz_line2.part3 field is required',
  1218: 'The passport.mrz_line2.part3 must be a string',
  1219: 'The passport.mrz_line2.part3 must be X characters',
  1220: 'The passport.mrz_line2.part4 field is required',
  1221: 'The passport.mrz_line2.part4 must be a string',
  1222: 'The passport.mrz_line2.part4 must be X characters',
  1223: 'The passport.mrz_line2.part5 field is required',
  1224: 'The passport.mrz_line2.part5 must be a string',
  1225: 'The passport.mrz_line2.part5 must be X characters',
  1226: 'The passport.mrz_line2.part6 field is required',
  1227: 'The passport.mrz_line2.part6 must be a string',
  1228: 'The passport.mrz_line2.part6 must be X characters',
  1229: 'The passport.mrz_line2.part7 field is required',
  1230: 'The passport.mrz_line2.part7 must be a string',
  1231: 'The passport.mrz_line2.part7 must be X characters',
  1232: 'The passport.mrz_line2.part8 field is required',
  1233: 'The passport.mrz_line2.part8 must be a string',
  1234: 'The passport.mrz_line2.part8 must be X characters',
  1235: 'The dob must be a string',
  1236: 'The driving_licence_number field is required',
  1237: 'The driving_licence_number must be a string',
  1238: 'The driving_licence_number must be at least X characters',
  1239: 'The driving_licence_number must not be greater than X characters',
  1240: 'The dob does not match the format X',
  1241: 'The scorecard is attached to a report type - please remove from report type before deleting',
  1242: 'The incoming data cannot overwrite existing input',
  1243: 'The report_type_id field is prohibited',
  1245: 'The uklexid must be an integer',
  1246: 'The dob must represent an age of 18 or over',
  1247: 'The include_deleted must be an integer',
  1248: 'The include_deleted must be between X and X characters',
  1249: 'The request returned too many records - please refine your search',
  1250: 'The reference field is required',
  1251: 'The reference_required field must be true or false',
  1252: 'The dob must represent an age of less than 115',
  1253: 'The nfi_address field must be true or false',
  1254: 'The nfi_amberhill field must be true or false',
  1255: 'The driving_licence_number field is required when none of X are present',
  1257: 'The config.nfi_address field must be true or false',
  1258: 'The nfi_address_avt must be an integer',
  1259: 'The nfi_amberhill_avt must be an integer',
  1260: 'The id_card_number must not be greater than X characters',
  1261: 'The nhs_number must not be greater than X characters',
  1262: 'The ni_number must not be greater than X characters',
  1263: 'The passport.number must not be greater than X characters',
  1264: 'The travel_visa_number must not be greater than X characters',
  1265: 'The remote_check field must be true or false',
  1266: 'The property_register_search field must be true or false',
  1267: 'The transactionId field is required',
  1268: 'The event field is required',
  1269: 'The selected event is invalid',
  1270: 'The user has already been migrated',
  1271: 'Subuser migration is not supported',
  1272: 'The phone_code format is invalid',
  1273: 'The phone_code must not be greater than X characters',
  1274: 'The phone_number format is invalid',
  1275: 'The phone_number must be at least X characters',
  1276: 'The phone_number must not be greater than X characters',
  1277: 'The phone_code field is required when X is present',
  1278: 'The phone_number field is required when X is present',
  1279: 'The selected config.flow_type is invalid',
  1280: 'The config.flow_type field is required',
  1281: 'The read field is required',
  1282: 'The read field must be true or false',
  1283: 'The otp_email field must be true or false',
  1284: 'The phone_code field is required',
  1285: 'The phone_number field is required',
  1286: 'The forename contains invalid characters',
  1287: 'The surname contains invalid characters',
  1288: 'The middlename contains invalid characters',
  1289: 'The email field is required',
  1290: 'The email must be a valid email address',
  1291: 'The otp_sms field must be true or false',
  1292: 'The code field is required',
  1293: 'The code must be X digits',
  1294: 'An OTP code must be generated first',
  1295: 'The notification_webhook_url format is invalid',
  1296: 'The notification_webhook_url is invalid',
  1297: 'The notification_webhook_url must have a valid SSL certificate',
  1298: 'The phone_match field must be true or false',
  1299: 'The date_from field is required',
  1300: 'The date_to must be a date after or equal to X',
  1301: 'The webhook URL is not configured for this user',
  1302: 'The phone_number_validation field must be true or false',
  1303: 'A webhook must be in a failed or retrying state to retry it',
  1304: 'The telephone must be a string',
  1305: 'The extension must be a string',
  1306: 'The mobile must be a string',
  1307: 'The telephone must not be greater than X characters',
  1308: 'The extension must not be greater than X characters',
  1309: 'The mobile must not be greater than X characters',
  1310: 'The email must not be greater than X characters',
  1311: 'The webdev_email must be a valid email address',
  1312: 'An active remote check journey exists - please cancel it first before creating a new one',
  1313: 'You cannot add another remote check to this report as one has already been completed',
  1314: 'The username format is invalid',
  1315: 'The telephone format is invalid',
  1316: 'The extension format is invalid',
  1317: 'The mobile format is invalid',
  1318: 'The username has already been taken',
  1319: 'The request contains invalid parameters',
  1320: 'The username field is required',
  1321: 'There is no active remote check transaction that can be cancelled',
  1322: 'The notification_webhook_url field is required',
  1323: 'The notification_webhook_secret field is required',
  1324: 'The status must be between X and X characters',
  1325: 'The report is closed for additional follow-up actions',
  1326: 'This template name is already taken. Please choose another name',
  1327: 'The report type name has already been taken',
  1328: 'The bridger_client_id must be a string',
  1329: 'The bridger_client_id must not be greater than X characters',
  1330: 'The bridger_client_secret must be a string',
  1331: 'The bridger_client_secret must not be greater than X characters',
  1332: 'The bridger_predefined_search must be a string',
  1333: 'The bridger_predefined_search must not be greater than X characters',
  1334: 'The bridger_user_id must be a string',
  1335: 'The bridger_user_id must not be greater than X characters',
  1336: 'The bridger_customer_toggle field must be true or false',
  1337: 'The bridger_client_secret must be at least X characters',
  1338: 'You cannot resend as the remote check transaction is no longer in progress',
  1339: 'The search must be a string',
  1340: 'The search must not be greater than X characters',
  1341: 'The phone_number must be a string',
  1342: 'The phone_code must be a string',
  1343: 'The secondary_actions must be an array',
  1344: 'The X report action does not exist',
  1345: 'The secondary_actions field has a duplicate value',
  1346: 'The X report action is not enabled for your user',
  1347: 'The X report action cannot appear in both primary and secondary actions',
  1348: 'The X report action cannot appear in both primary and secondary actions',
};

export function errorMessage(code: number): string {
  const message = ERROR_CODES[code];
  if (!message) {
    throw new Error(`Unknown error code: ${code}`);
  }
  return message;
}
