apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-ssm-store
  namespace: deploy
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: secrets-sa
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lexis-nexis-secret
  namespace: deploy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm-store
    kind: SecretStore
  target:
    name: lexis-nexis-secret
    creationPolicy: Owner

  data:
    - secretKey: CLIENT_PROVISION_KEY
      remoteRef:
        key: /matchx/dev/CLIENT_PROVISION_KEY

    # - secretKey: DATABASE_URL
    #   remoteRef:
    #     key: /matchx/prod/database_url

    - secretKey: RATE_LIMIT_PER_SECOND
      remoteRef:
        key: /matchx/dev/RATE_LIMIT_PER_SECOND

    - secretKey: THROTTLE_MODE
      remoteRef:
        key: /matchx/dev/THROTTLE_MODE