apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matchx-lexis-nexis-ingress
  namespace: deploy
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
  tls:
    - hosts:
        - dev.matchx.blue
      secretName: matchx-blue-tls-secret

  rules:
    - host: dev.matchx.blue
      http:
        paths:
          - path: /lexis-nexis
            pathType: Prefix
            backend:
              service:
                name: matchx-lexis-nexis-service
                port:
                  number: 80