apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-ssm-store
  namespace: matchx
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: secrets-sa
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lexis-nexis-secret
  namespace: matchx
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm-store
    kind: SecretStore
  target:
    name: lexis-nexis-secret
    creationPolicy: Owner

  data:
    - secretKey: CLIENT_PROVISION_KEY
      remoteRef:
        key: /matchx/prod/CLIENT_PROVISION_KEY
