import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { createApp } from '../src/app.js';
import { collectRoutes } from '../src/lib/openapi/collectRoutes.js';
import { EXTENSION_ROUTES } from '../src/lib/openapi/extensions.js';

/**
 * Generates docs/openapi.json from the replica's own live routes —
 * structure only (paths/methods/extension-tagging), NOT full request/
 * response schema fidelity (see the spec's own `description`). This is
 * the artifact EPIC-8's doc-parity test diffs the live route surface
 * against in CI; re-run this script and commit the result whenever a
 * route is added, removed, or renamed.
 */
function main(): void {
  const app = createApp();
  const routes = collectRoutes(app);

  const paths: Record<string, Record<string, unknown>> = {};
  for (const { method, path } of routes) {
    const openApiPath = path.replace(/:([A-Za-z0-9_]+)/g, '{$1}');
    const isExtension = EXTENSION_ROUTES.some(
      (route) => route.method === method && route.path === path,
    );
    paths[openApiPath] = paths[openApiPath] ?? {};
    paths[openApiPath][method.toLowerCase()] = {
      tags: [isExtension ? 'extension' : 'documented'],
      ...(isExtension && {
        summary: 'Replica-only extension — not part of the documented API (see README.md).',
      }),
      responses: { '200': { description: "See planning/specs for this route's response shape." } },
    };
  }

  const spec = {
    openapi: '3.0.3',
    info: {
      title: 'LN Replica (generated)',
      version: '0.1.0',
      description:
        'Structure-only (paths/methods/extension-tagging) — NOT full request/response schema fidelity. ' +
        "Generated by scripts/generate-openapi.ts from the replica's own live routes. The one-time human " +
        'cross-check against the real IDU_REST_API_Documentation.pdf stays a manual step (see constitution.md).',
    },
    paths,
  };

  const outputPath = fileURLToPath(new URL('../docs/openapi.json', import.meta.url));
  writeFileSync(outputPath, `${JSON.stringify(spec, null, 2)}\n`);
  console.log(
    `Wrote docs/openapi.json with ${routes.length} routes (${EXTENSION_ROUTES.length} extensions).`,
  );
}

main();
